import FormWrapper from "@/app/contact/contact-form";
import {Metadata} from "next";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function ContactPage() {
  return (
    <FormWrapper/>
  )
}